---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bob-node
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: dscp-node
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-dscp-node.yaml
  interval: 10m
