apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: match2
resources:
  - yellow-node
  - green-node
  - ipfs-node
  - identity-service
  - matchmaker-api
  - nginx
  - open-api-merger
  - chainspec-configmap.yaml
  - source.yaml
configMapGenerator:
  - name: match2-values
    files:
      - values-yellow.yaml=yellow-node/values.yaml
      - values-green.yaml=green-node/values.yaml
      - values-ipfs.yaml=ipfs-node/values.yaml
      - values-identity-service.yaml=identity-service/values.yaml
      - values-matchmaker-api.yaml=matchmaker-api/values.yaml
      - values-nginx.yaml=nginx/values.yaml
      - values-open-api-merger.yaml=open-api-merger/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
