---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: monitoring
spec:
  install:
    remediation:
      retries: -1
  releaseName: nginx-ingress-controller
  chart:
    spec:
      version: 11.3.0
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: nginx-values.yaml