apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vitalam
resources:
  - source.yaml
  - release.yaml
configMapGenerator:
  - name: vitalam-node-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true