---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vitalam-node
  namespace: vitalam
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: node
      sourceRef:
        kind: HelmRepository
        name: parity
      version: 0.20.0
  valuesFrom:
  - kind: ConfigMap
    name: vitalam-node-values
    valuesKey: values.yaml
  interval: 10m0s
