image: 
  repository: ghcr.io/digicatapult/vitalam-node
  tag: latest
  pullPolicy: IfNotPresent

node:
  chain: "local"
  command: "./vitalam-node"
  dataVolumeSize: 1Gi
  flags:
    - "--alice"
    - "--ws-port 9944"
    - "--rpc-port 9933"
    - "--port 30333"
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=safe"
    - "--rpc-cors=all"
    - "--prometheus-external"
  keys: 
    - type: "gran"
      scheme: "ed25519"
      seed: "//Alice"
    - type: "aura"
      scheme: "sr25519"
      seed: "//Alice"
storageClass: "standard"