---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: optimiser
spec:
  install:
    remediation:
      retries: -1
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: optimiser-values
      valuesKey: values-nginx.yaml
