apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: oauth2-proxy-values
    files:
      - values.yaml
