---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bob-identity-service
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: bob-node
  chart:
    spec:
      chart: dscp-identity-service
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-dscp-identity-service.yaml
  interval: 10m0s
