---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alice-sync
  namespace: alice
spec:
  interval: 1m
  path: ./clusters/kind-cluster/alice
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bob-sync
  namespace: bob
spec:
  interval: 1m
  path: ./clusters/kind-cluster/bob
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charlie-sync
  namespace: charlie
spec:
  interval: 1m
  path: ./clusters/kind-cluster/charlie
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-sync
  namespace: kube-system
spec:
  interval: 1m
  path: ./clusters/kind-cluster/nginx
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-sync
  namespace: monitoring
spec:
  interval: 1m
  path: ./clusters/kind-cluster/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-sync
  namespace: keycloak
spec:
  interval: 1m
  path: ./clusters/kind-cluster/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-sync
  namespace: loki
spec:
  interval: 1m
  path: ./clusters/kind-cluster/loki
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: promtail-sync
  namespace: loki
spec:
  interval: 1m
  path: ./clusters/kind-cluster/promtail
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
