---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alice-sync
  namespace: alice
spec:
  interval: 1m
  path: ./clusters/kind-cluster/alice
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bob-sync
  namespace: bob
spec:
  interval: 1m
  path: ./clusters/kind-cluster/bob
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charlie-sync
  namespace: charlie
spec:
  interval: 1m
  path: ./clusters/kind-cluster/charlie
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-sync
  namespace: kube-system
spec:
  interval: 1m
  path: ./clusters/kind-cluster/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
