apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: sqnc
    app.kubernetes.io/version: latest
  name: alice
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: sqnc
    app.kubernetes.io/version: latest
  name: bob
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: sqnc
    app.kubernetes.io/version: latest
  name: charlie
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: sqnc
    app.kubernetes.io/version: latest
  name: ory
