apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - source.yaml
  - release.yaml
  - monitoring-podmonitor-sync.yaml
configMapGenerator:
  - name: monitoring-values
    files:
      - values.yaml
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
