# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
alertmanager:
  enabled: true
  serviceMonitor:
    selfMonitor: true
    namespace: monitoring
prometheus:
  serviceMonitor:
    selfMonitor: true
    namespace: monitoring
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: { }
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: { }
    podMonitorSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring
grafana:
  defaultDashboardsEnabled: false
  serviceMonitor:
    enabled: true
    namespace: monitoring
  persistence:
    enabled: true
  adminPassword: grafana
  plugins:
    - camptocamp-prometheus-alertmanager-datasource
  additionalDataSources:
    - name: "Prometheus AlertManager"
      type: camptocamp-prometheus-alertmanager-datasource
      uid: prometheus-alertmanager
      url: http://{{ template "kube-prometheus-stack.fullname" . }}-alertmanager.{{ template "kube-prometheus-stack.namespace" . }}:{{ .Values.alertmanager.service.port }}/{{ trimPrefix "/" .Values.alertmanager.alertmanagerSpec.routePrefix }}
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
  dashboards:
    default:
      postgresql:
        gnetId: 9628
        revision: 7
        datasource: Prometheus
      nginx:
        gnetId: 9614
        revision: 1
        datasource: Prometheus
      flux2:
        gnetId: 16714
        revision: 1
        datasource: Prometheus
      alertmanager:
        gnetId: 9578
        revision: 4
        datasource: Prometheus
      polkadot:
        gnetId: 13840
        revision: 4
        datasource: Prometheus
