---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/add-oauth2-proxy
  url: https://github.com/digicatapult/sqnc-flux-infra.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kind-cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
