---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: bug/ingress-controllers
  secretRef:
    name: flux-system
  url: https://github.com/digicatapult/dscp-flux-infra.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/kind-cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
