---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/parity-substrate-node
  secretRef:
    name: flux-system
  url: https://github.com/digicatapult/vitalam-flux-infra.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kind-cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
