---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: digicatapult
  namespace: alice
spec:
  interval: 10m
  url: https://digicatapult.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: alice
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
