---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bob-dscp-api
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: bob-ipfs
  chart:
    spec:
      chart: dscp-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-dscp-api.yaml
  interval: 10m0s
