apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: oathkeeper-authenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<alice|bob|charlie>/<sqnc-matchmaker-api|sqnc-identity-service>/<v1|v3>/<(?!swagger|api-docs).*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: oauth2_introspection
      config:
        introspection_url: 'http://hydra-admin:4445/oauth2/introspect'
        scope_strategy: wildcard
        cache:
          enabled: false
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: oathkeeper-unauthenticated-paths
  namespace: ory
spec:
  match:
    url: <.*>/<(swagger|api-docs).*>
    methods:
      - GET
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
