---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oathkeeper
  namespace: ory
spec:
  install:
    remediation:
      retries: -1
  releaseName: oathkeeper
  chart:
    spec:
      chart: oathkeeper
      sourceRef:
        kind: HelmRepository
        name: ory
  interval: 1m0s
  dependsOn:
    - name: oathkeeper-maester
  # Default values
  # https://github.com/ory/k8s/blob/master/helm/charts/hydra/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: oathkeeper-values
