---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: charlie-node
  namespace: charlie
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: dscp-node
      version: "4.2.1"
      sourceRef:
        kind: HelmRepository
        name: dscp-node
  valuesFrom:
  - kind: ConfigMap
    name: charlie-values
    valuesKey: values-dscp-node.yaml
  interval: 10m
