---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alice-dscp-api
  namespace: alice
spec:
  install:
    remediation:
      retries: -1
  dependsOn: 
    - name: alice-ipfs
  chart:
    spec:
      chart: dscp-api
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  valuesFrom:
  - kind: ConfigMap
    name: alice-values
    valuesKey: values-dscp-api.yaml
  interval: 10m0s
