---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-sync
  namespace: monitoring
spec:
  interval: 1m
  path: ./clusters/sqnc-staging/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: capacity-sync
#   namespace: capacity
# spec:
#   interval: 1m
#   path: ./clusters/l3-sqnc/capacity
#   prune: true
#   dependsOn:
#     - name: monitoring-sync
#       namespace: monitoring
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: optimiser-sync
#   namespace: optimiser
# spec:
#   interval: 1m
#   path: ./clusters/l3-sqnc/optimiser
#   prune: true
#   dependsOn:
#     - name: monitoring-sync
#       namespace: monitoring
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: order-sync
#   namespace: order
# spec:
#   interval: 1m
#   path: ./clusters/l3-sqnc/order
#   prune: true
#   dependsOn:
#     - name: monitoring-sync
#       namespace: monitoring
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-sync 
  namespace: cert-manager 
spec:
  interval: 1m
  path: ./clusters/sqnc-staging/cert-manager
  prune: true
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-sync
  namespace: keycloak
spec:
  interval: 1m
  path: ./clusters/sqnc-staging/keycloak 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
